// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ai.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<StructuredNoteResult> generateStructuredNote({
  required StructuredNoteRequest request,
}) =>
    RustLib.instance.api.crateApiAiApiGenerateStructuredNote(request: request);

Future<AiTextResult> mergeDailyNote({required DailyMergeRequest request}) =>
    RustLib.instance.api.crateApiAiApiMergeDailyNote(request: request);

Future<AiTextResult> generateWeeklyReport({required ReportRequest request}) =>
    RustLib.instance.api.crateApiAiApiGenerateWeeklyReport(request: request);

Future<AiTextResult> generateMonthlyReport({required ReportRequest request}) =>
    RustLib.instance.api.crateApiAiApiGenerateMonthlyReport(request: request);

Future<AiTextResult> memoryChat({required MemoryChatRequest request}) =>
    RustLib.instance.api.crateApiAiApiMemoryChat(request: request);

Future<AiTextResult> fimComplete({required FimCompleteRequest request}) =>
    RustLib.instance.api.crateApiAiApiFimComplete(request: request);

Future<ProviderTestResult> testProviderConnection({
  required String appDataDir,
  required AiProvider provider,
  required AiModel model,
  required bool apiLogEnabled,
}) => RustLib.instance.api.crateApiAiApiTestProviderConnection(
  appDataDir: appDataDir,
  provider: provider,
  model: model,
  apiLogEnabled: apiLogEnabled,
);

Future<ModelListResult> fetchProviderModels({
  required String appDataDir,
  required AiProvider provider,
  required bool apiLogEnabled,
}) => RustLib.instance.api.crateApiAiApiFetchProviderModels(
  appDataDir: appDataDir,
  provider: provider,
  apiLogEnabled: apiLogEnabled,
);
