// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../cloud_sync.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<CloudSyncResult> testWebDavConnection({
  required CloudSyncConfig config,
}) => RustLib.instance.api.crateApiCloudSyncApiTestWebDavConnection(
  config: config,
);

Future<CloudSyncResult> syncWebDavNotes({required CloudSyncRequest request}) =>
    RustLib.instance.api.crateApiCloudSyncApiSyncWebDavNotes(request: request);

Future<CloudSyncResult> uploadWebDavNote({
  required CloudSyncNoteUploadRequest request,
}) =>
    RustLib.instance.api.crateApiCloudSyncApiUploadWebDavNote(request: request);
