// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AiModel {
  final String modelId;
  final String displayName;

  const AiModel({required this.modelId, required this.displayName});

  @override
  int get hashCode => modelId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiModel &&
          runtimeType == other.runtimeType &&
          modelId == other.modelId &&
          displayName == other.displayName;
}

class AiProvider {
  final String id;
  final String name;
  final String protocol;
  final String apiKey;
  final String baseUrl;
  final String apiPath;

  const AiProvider({
    required this.id,
    required this.name,
    required this.protocol,
    required this.apiKey,
    required this.baseUrl,
    required this.apiPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      protocol.hashCode ^
      apiKey.hashCode ^
      baseUrl.hashCode ^
      apiPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiProvider &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          protocol == other.protocol &&
          apiKey == other.apiKey &&
          baseUrl == other.baseUrl &&
          apiPath == other.apiPath;
}

class AiTextResult {
  final bool ok;
  final String content;
  final String errorCode;
  final String errorMessage;
  final int inputTokens;
  final int outputTokens;
  final int cachedTokens;
  final String providerName;
  final String modelId;

  const AiTextResult({
    required this.ok,
    required this.content,
    required this.errorCode,
    required this.errorMessage,
    required this.inputTokens,
    required this.outputTokens,
    required this.cachedTokens,
    required this.providerName,
    required this.modelId,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      content.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      cachedTokens.hashCode ^
      providerName.hashCode ^
      modelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiTextResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          content == other.content &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          cachedTokens == other.cachedTokens &&
          providerName == other.providerName &&
          modelId == other.modelId;
}

class DailyMergeRequest {
  final String appDataDir;
  final AiProvider provider;
  final AiModel model;
  final String existingMarkdown;
  final String rawInput;
  final List<String> completed;
  final List<String> issues;
  final List<String> plans;
  final String date;
  final bool apiLogEnabled;

  const DailyMergeRequest({
    required this.appDataDir,
    required this.provider,
    required this.model,
    required this.existingMarkdown,
    required this.rawInput,
    required this.completed,
    required this.issues,
    required this.plans,
    required this.date,
    required this.apiLogEnabled,
  });

  @override
  int get hashCode =>
      appDataDir.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      existingMarkdown.hashCode ^
      rawInput.hashCode ^
      completed.hashCode ^
      issues.hashCode ^
      plans.hashCode ^
      date.hashCode ^
      apiLogEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyMergeRequest &&
          runtimeType == other.runtimeType &&
          appDataDir == other.appDataDir &&
          provider == other.provider &&
          model == other.model &&
          existingMarkdown == other.existingMarkdown &&
          rawInput == other.rawInput &&
          completed == other.completed &&
          issues == other.issues &&
          plans == other.plans &&
          date == other.date &&
          apiLogEnabled == other.apiLogEnabled;
}

class FimCompleteRequest {
  final String appDataDir;
  final AiProvider provider;
  final AiModel model;
  final String prompt;
  final String suffix;
  final bool apiLogEnabled;

  const FimCompleteRequest({
    required this.appDataDir,
    required this.provider,
    required this.model,
    required this.prompt,
    required this.suffix,
    required this.apiLogEnabled,
  });

  @override
  int get hashCode =>
      appDataDir.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      prompt.hashCode ^
      suffix.hashCode ^
      apiLogEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FimCompleteRequest &&
          runtimeType == other.runtimeType &&
          appDataDir == other.appDataDir &&
          provider == other.provider &&
          model == other.model &&
          prompt == other.prompt &&
          suffix == other.suffix &&
          apiLogEnabled == other.apiLogEnabled;
}

class MemoryChatRequest {
  final String appDataDir;
  final AiProvider provider;
  final AiModel model;
  final String question;
  final String contextMarkdown;
  final bool apiLogEnabled;

  const MemoryChatRequest({
    required this.appDataDir,
    required this.provider,
    required this.model,
    required this.question,
    required this.contextMarkdown,
    required this.apiLogEnabled,
  });

  @override
  int get hashCode =>
      appDataDir.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      question.hashCode ^
      contextMarkdown.hashCode ^
      apiLogEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryChatRequest &&
          runtimeType == other.runtimeType &&
          appDataDir == other.appDataDir &&
          provider == other.provider &&
          model == other.model &&
          question == other.question &&
          contextMarkdown == other.contextMarkdown &&
          apiLogEnabled == other.apiLogEnabled;
}

class ModelListResult {
  final bool ok;
  final List<AiModel> models;
  final String errorCode;
  final String errorMessage;

  const ModelListResult({
    required this.ok,
    required this.models,
    required this.errorCode,
    required this.errorMessage,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      models.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelListResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          models == other.models &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage;
}

class ProviderTestResult {
  final bool ok;
  final String message;
  final String errorCode;

  const ProviderTestResult({
    required this.ok,
    required this.message,
    required this.errorCode,
  });

  @override
  int get hashCode => ok.hashCode ^ message.hashCode ^ errorCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderTestResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          message == other.message &&
          errorCode == other.errorCode;
}

class ReportRequest {
  final String appDataDir;
  final AiProvider provider;
  final AiModel model;
  final String sourceMarkdown;
  final String periodLabel;
  final bool apiLogEnabled;

  const ReportRequest({
    required this.appDataDir,
    required this.provider,
    required this.model,
    required this.sourceMarkdown,
    required this.periodLabel,
    required this.apiLogEnabled,
  });

  @override
  int get hashCode =>
      appDataDir.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      sourceMarkdown.hashCode ^
      periodLabel.hashCode ^
      apiLogEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReportRequest &&
          runtimeType == other.runtimeType &&
          appDataDir == other.appDataDir &&
          provider == other.provider &&
          model == other.model &&
          sourceMarkdown == other.sourceMarkdown &&
          periodLabel == other.periodLabel &&
          apiLogEnabled == other.apiLogEnabled;
}

class StructuredNoteRequest {
  final String appDataDir;
  final AiProvider provider;
  final AiModel model;
  final String input;
  final bool apiLogEnabled;

  const StructuredNoteRequest({
    required this.appDataDir,
    required this.provider,
    required this.model,
    required this.input,
    required this.apiLogEnabled,
  });

  @override
  int get hashCode =>
      appDataDir.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      input.hashCode ^
      apiLogEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredNoteRequest &&
          runtimeType == other.runtimeType &&
          appDataDir == other.appDataDir &&
          provider == other.provider &&
          model == other.model &&
          input == other.input &&
          apiLogEnabled == other.apiLogEnabled;
}

class StructuredNoteResult {
  final bool ok;
  final List<String> completed;
  final List<String> issues;
  final List<String> plans;
  final String rawContent;
  final String errorCode;
  final String errorMessage;
  final int inputTokens;
  final int outputTokens;
  final int cachedTokens;

  const StructuredNoteResult({
    required this.ok,
    required this.completed,
    required this.issues,
    required this.plans,
    required this.rawContent,
    required this.errorCode,
    required this.errorMessage,
    required this.inputTokens,
    required this.outputTokens,
    required this.cachedTokens,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      completed.hashCode ^
      issues.hashCode ^
      plans.hashCode ^
      rawContent.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      cachedTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredNoteResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          completed == other.completed &&
          issues == other.issues &&
          plans == other.plans &&
          rawContent == other.rawContent &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          cachedTokens == other.cachedTokens;
}
