// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CloudSyncConfig {
  final bool enabled;
  final String serverUrl;
  final String username;
  final String password;

  const CloudSyncConfig({
    required this.enabled,
    required this.serverUrl,
    required this.username,
    required this.password,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      serverUrl.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          serverUrl == other.serverUrl &&
          username == other.username &&
          password == other.password;
}

class DeleteModifyConflict {
  final String relativePath;
  final String direction;

  const DeleteModifyConflict({
    required this.relativePath,
    required this.direction,
  });

  @override
  int get hashCode => relativePath.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteModifyConflict &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          direction == other.direction;
}

class CloudSyncNoteUploadRequest {
  final CloudSyncConfig config;
  final String dataDirectory;
  final String dailyNotesDirectory;
  final String weeklyNotesDirectory;
  final String monthlyNotesDirectory;
  final String notePath;

  const CloudSyncNoteUploadRequest({
    required this.config,
    required this.dataDirectory,
    required this.dailyNotesDirectory,
    required this.weeklyNotesDirectory,
    required this.monthlyNotesDirectory,
    required this.notePath,
  });

  @override
  int get hashCode =>
      config.hashCode ^
      dataDirectory.hashCode ^
      dailyNotesDirectory.hashCode ^
      weeklyNotesDirectory.hashCode ^
      monthlyNotesDirectory.hashCode ^
      notePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncNoteUploadRequest &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          dataDirectory == other.dataDirectory &&
          dailyNotesDirectory == other.dailyNotesDirectory &&
          weeklyNotesDirectory == other.weeklyNotesDirectory &&
          monthlyNotesDirectory == other.monthlyNotesDirectory &&
          notePath == other.notePath;
}

class CloudSyncRequest {
  final CloudSyncConfig config;
  final String dataDirectory;
  final String dailyNotesDirectory;
  final String weeklyNotesDirectory;
  final String monthlyNotesDirectory;
  final String trigger;
  final List<String> confirmedDeleteLocal;
  final List<String> confirmedDeleteRemote;
  final List<String> confirmedOverwriteLocal;
  final List<String> confirmedOverwriteRemote;
  final List<String> skippedDeleteModifyConflicts;

  const CloudSyncRequest({
    required this.config,
    required this.dataDirectory,
    required this.dailyNotesDirectory,
    required this.weeklyNotesDirectory,
    required this.monthlyNotesDirectory,
    required this.trigger,
    required this.confirmedDeleteLocal,
    required this.confirmedDeleteRemote,
    required this.confirmedOverwriteLocal,
    required this.confirmedOverwriteRemote,
    required this.skippedDeleteModifyConflicts,
  });

  @override
  int get hashCode =>
      config.hashCode ^
      dataDirectory.hashCode ^
      dailyNotesDirectory.hashCode ^
      weeklyNotesDirectory.hashCode ^
      monthlyNotesDirectory.hashCode ^
      trigger.hashCode ^
      confirmedDeleteLocal.hashCode ^
      confirmedDeleteRemote.hashCode ^
      confirmedOverwriteLocal.hashCode ^
      confirmedOverwriteRemote.hashCode ^
      skippedDeleteModifyConflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncRequest &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          dataDirectory == other.dataDirectory &&
          dailyNotesDirectory == other.dailyNotesDirectory &&
          weeklyNotesDirectory == other.weeklyNotesDirectory &&
          monthlyNotesDirectory == other.monthlyNotesDirectory &&
          trigger == other.trigger &&
          confirmedDeleteLocal == other.confirmedDeleteLocal &&
          confirmedDeleteRemote == other.confirmedDeleteRemote &&
          confirmedOverwriteLocal == other.confirmedOverwriteLocal &&
          confirmedOverwriteRemote == other.confirmedOverwriteRemote &&
          skippedDeleteModifyConflicts == other.skippedDeleteModifyConflicts;
}

class CloudSyncResult {
  final bool ok;
  final String message;
  final int uploaded;
  final int downloaded;
  final int conflicts;
  final String syncedAt;
  final String errorCode;
  final bool needsDeleteConfirmation;
  final List<String> pendingDeleteLocal;
  final List<String> pendingDeleteRemote;
  final bool needsDeleteModifyConfirmation;
  final List<DeleteModifyConflict> pendingDeleteModifyConflicts;

  const CloudSyncResult({
    required this.ok,
    required this.message,
    required this.uploaded,
    required this.downloaded,
    required this.conflicts,
    required this.syncedAt,
    required this.errorCode,
    required this.needsDeleteConfirmation,
    required this.pendingDeleteLocal,
    required this.pendingDeleteRemote,
    required this.needsDeleteModifyConfirmation,
    required this.pendingDeleteModifyConflicts,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      message.hashCode ^
      uploaded.hashCode ^
      downloaded.hashCode ^
      conflicts.hashCode ^
      syncedAt.hashCode ^
      errorCode.hashCode ^
      needsDeleteConfirmation.hashCode ^
      pendingDeleteLocal.hashCode ^
      pendingDeleteRemote.hashCode ^
      needsDeleteModifyConfirmation.hashCode ^
      pendingDeleteModifyConflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          message == other.message &&
          uploaded == other.uploaded &&
          downloaded == other.downloaded &&
          conflicts == other.conflicts &&
          syncedAt == other.syncedAt &&
          errorCode == other.errorCode &&
          needsDeleteConfirmation == other.needsDeleteConfirmation &&
          pendingDeleteLocal == other.pendingDeleteLocal &&
          pendingDeleteRemote == other.pendingDeleteRemote &&
          needsDeleteModifyConfirmation ==
              other.needsDeleteModifyConfirmation &&
          pendingDeleteModifyConflicts == other.pendingDeleteModifyConflicts;
}
