// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'ai.dart';
import 'api/ai_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiModel dco_decode_ai_model(dynamic raw);

  @protected
  AiProvider dco_decode_ai_provider(dynamic raw);

  @protected
  AiTextResult dco_decode_ai_text_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiModel dco_decode_box_autoadd_ai_model(dynamic raw);

  @protected
  AiProvider dco_decode_box_autoadd_ai_provider(dynamic raw);

  @protected
  DailyMergeRequest dco_decode_box_autoadd_daily_merge_request(dynamic raw);

  @protected
  FimCompleteRequest dco_decode_box_autoadd_fim_complete_request(dynamic raw);

  @protected
  MemoryChatRequest dco_decode_box_autoadd_memory_chat_request(dynamic raw);

  @protected
  ReportRequest dco_decode_box_autoadd_report_request(dynamic raw);

  @protected
  StructuredNoteRequest dco_decode_box_autoadd_structured_note_request(
    dynamic raw,
  );

  @protected
  DailyMergeRequest dco_decode_daily_merge_request(dynamic raw);

  @protected
  FimCompleteRequest dco_decode_fim_complete_request(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiModel> dco_decode_list_ai_model(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MemoryChatRequest dco_decode_memory_chat_request(dynamic raw);

  @protected
  ModelListResult dco_decode_model_list_result(dynamic raw);

  @protected
  ProviderTestResult dco_decode_provider_test_result(dynamic raw);

  @protected
  ReportRequest dco_decode_report_request(dynamic raw);

  @protected
  StructuredNoteRequest dco_decode_structured_note_request(dynamic raw);

  @protected
  StructuredNoteResult dco_decode_structured_note_result(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiModel sse_decode_ai_model(SseDeserializer deserializer);

  @protected
  AiProvider sse_decode_ai_provider(SseDeserializer deserializer);

  @protected
  AiTextResult sse_decode_ai_text_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiModel sse_decode_box_autoadd_ai_model(SseDeserializer deserializer);

  @protected
  AiProvider sse_decode_box_autoadd_ai_provider(SseDeserializer deserializer);

  @protected
  DailyMergeRequest sse_decode_box_autoadd_daily_merge_request(
    SseDeserializer deserializer,
  );

  @protected
  FimCompleteRequest sse_decode_box_autoadd_fim_complete_request(
    SseDeserializer deserializer,
  );

  @protected
  MemoryChatRequest sse_decode_box_autoadd_memory_chat_request(
    SseDeserializer deserializer,
  );

  @protected
  ReportRequest sse_decode_box_autoadd_report_request(
    SseDeserializer deserializer,
  );

  @protected
  StructuredNoteRequest sse_decode_box_autoadd_structured_note_request(
    SseDeserializer deserializer,
  );

  @protected
  DailyMergeRequest sse_decode_daily_merge_request(
    SseDeserializer deserializer,
  );

  @protected
  FimCompleteRequest sse_decode_fim_complete_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiModel> sse_decode_list_ai_model(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MemoryChatRequest sse_decode_memory_chat_request(
    SseDeserializer deserializer,
  );

  @protected
  ModelListResult sse_decode_model_list_result(SseDeserializer deserializer);

  @protected
  ProviderTestResult sse_decode_provider_test_result(
    SseDeserializer deserializer,
  );

  @protected
  ReportRequest sse_decode_report_request(SseDeserializer deserializer);

  @protected
  StructuredNoteRequest sse_decode_structured_note_request(
    SseDeserializer deserializer,
  );

  @protected
  StructuredNoteResult sse_decode_structured_note_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_model(AiModel self, SseSerializer serializer);

  @protected
  void sse_encode_ai_provider(AiProvider self, SseSerializer serializer);

  @protected
  void sse_encode_ai_text_result(AiTextResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_model(AiModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_provider(
    AiProvider self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_daily_merge_request(
    DailyMergeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_fim_complete_request(
    FimCompleteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_memory_chat_request(
    MemoryChatRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_report_request(
    ReportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_structured_note_request(
    StructuredNoteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_daily_merge_request(
    DailyMergeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fim_complete_request(
    FimCompleteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_model(List<AiModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_chat_request(
    MemoryChatRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_list_result(
    ModelListResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_test_result(
    ProviderTestResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_report_request(ReportRequest self, SseSerializer serializer);

  @protected
  void sse_encode_structured_note_request(
    StructuredNoteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_structured_note_result(
    StructuredNoteResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
