// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'ai.dart';
import 'api/ai_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAiApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -154967618;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ModelListResult> crateApiAiApiFetchProviderModels({
    required String appDataDir,
    required AiProvider provider,
    required bool apiLogEnabled,
  });

  Future<AiTextResult> crateApiAiApiFimComplete({
    required FimCompleteRequest request,
  });

  Future<AiTextResult> crateApiAiApiGenerateMonthlyReport({
    required ReportRequest request,
  });

  Future<StructuredNoteResult> crateApiAiApiGenerateStructuredNote({
    required StructuredNoteRequest request,
  });

  Future<AiTextResult> crateApiAiApiGenerateWeeklyReport({
    required ReportRequest request,
  });

  Future<void> crateApiAiApiInitApp();

  Future<AiTextResult> crateApiAiApiMemoryChat({
    required MemoryChatRequest request,
  });

  Future<AiTextResult> crateApiAiApiMergeDailyNote({
    required DailyMergeRequest request,
  });

  Future<ProviderTestResult> crateApiAiApiTestProviderConnection({
    required String appDataDir,
    required AiProvider provider,
    required AiModel model,
    required bool apiLogEnabled,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ModelListResult> crateApiAiApiFetchProviderModels({
    required String appDataDir,
    required AiProvider provider,
    required bool apiLogEnabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appDataDir, serializer);
          sse_encode_box_autoadd_ai_provider(provider, serializer);
          sse_encode_bool(apiLogEnabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_model_list_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiFetchProviderModelsConstMeta,
        argValues: [appDataDir, provider, apiLogEnabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiFetchProviderModelsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_provider_models",
        argNames: ["appDataDir", "provider", "apiLogEnabled"],
      );

  @override
  Future<AiTextResult> crateApiAiApiFimComplete({
    required FimCompleteRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_fim_complete_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ai_text_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiFimCompleteConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiFimCompleteConstMeta =>
      const TaskConstMeta(debugName: "fim_complete", argNames: ["request"]);

  @override
  Future<AiTextResult> crateApiAiApiGenerateMonthlyReport({
    required ReportRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_report_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ai_text_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiGenerateMonthlyReportConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiGenerateMonthlyReportConstMeta =>
      const TaskConstMeta(
        debugName: "generate_monthly_report",
        argNames: ["request"],
      );

  @override
  Future<StructuredNoteResult> crateApiAiApiGenerateStructuredNote({
    required StructuredNoteRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_structured_note_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_structured_note_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiGenerateStructuredNoteConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiGenerateStructuredNoteConstMeta =>
      const TaskConstMeta(
        debugName: "generate_structured_note",
        argNames: ["request"],
      );

  @override
  Future<AiTextResult> crateApiAiApiGenerateWeeklyReport({
    required ReportRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_report_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ai_text_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiGenerateWeeklyReportConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiGenerateWeeklyReportConstMeta =>
      const TaskConstMeta(
        debugName: "generate_weekly_report",
        argNames: ["request"],
      );

  @override
  Future<void> crateApiAiApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<AiTextResult> crateApiAiApiMemoryChat({
    required MemoryChatRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_memory_chat_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ai_text_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiMemoryChatConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiMemoryChatConstMeta =>
      const TaskConstMeta(debugName: "memory_chat", argNames: ["request"]);

  @override
  Future<AiTextResult> crateApiAiApiMergeDailyNote({
    required DailyMergeRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_daily_merge_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ai_text_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiMergeDailyNoteConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiMergeDailyNoteConstMeta =>
      const TaskConstMeta(debugName: "merge_daily_note", argNames: ["request"]);

  @override
  Future<ProviderTestResult> crateApiAiApiTestProviderConnection({
    required String appDataDir,
    required AiProvider provider,
    required AiModel model,
    required bool apiLogEnabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appDataDir, serializer);
          sse_encode_box_autoadd_ai_provider(provider, serializer);
          sse_encode_box_autoadd_ai_model(model, serializer);
          sse_encode_bool(apiLogEnabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_provider_test_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApiTestProviderConnectionConstMeta,
        argValues: [appDataDir, provider, model, apiLogEnabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApiTestProviderConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "test_provider_connection",
        argNames: ["appDataDir", "provider", "model", "apiLogEnabled"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AiModel dco_decode_ai_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AiModel(
      modelId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
    );
  }

  @protected
  AiProvider dco_decode_ai_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AiProvider(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      protocol: dco_decode_String(arr[2]),
      apiKey: dco_decode_String(arr[3]),
      baseUrl: dco_decode_String(arr[4]),
      apiPath: dco_decode_String(arr[5]),
    );
  }

  @protected
  AiTextResult dco_decode_ai_text_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return AiTextResult(
      ok: dco_decode_bool(arr[0]),
      content: dco_decode_String(arr[1]),
      errorCode: dco_decode_String(arr[2]),
      errorMessage: dco_decode_String(arr[3]),
      inputTokens: dco_decode_i_32(arr[4]),
      outputTokens: dco_decode_i_32(arr[5]),
      cachedTokens: dco_decode_i_32(arr[6]),
      providerName: dco_decode_String(arr[7]),
      modelId: dco_decode_String(arr[8]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AiModel dco_decode_box_autoadd_ai_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ai_model(raw);
  }

  @protected
  AiProvider dco_decode_box_autoadd_ai_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ai_provider(raw);
  }

  @protected
  DailyMergeRequest dco_decode_box_autoadd_daily_merge_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_daily_merge_request(raw);
  }

  @protected
  FimCompleteRequest dco_decode_box_autoadd_fim_complete_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fim_complete_request(raw);
  }

  @protected
  MemoryChatRequest dco_decode_box_autoadd_memory_chat_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_memory_chat_request(raw);
  }

  @protected
  ReportRequest dco_decode_box_autoadd_report_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_report_request(raw);
  }

  @protected
  StructuredNoteRequest dco_decode_box_autoadd_structured_note_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_structured_note_request(raw);
  }

  @protected
  DailyMergeRequest dco_decode_daily_merge_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return DailyMergeRequest(
      appDataDir: dco_decode_String(arr[0]),
      provider: dco_decode_ai_provider(arr[1]),
      model: dco_decode_ai_model(arr[2]),
      existingMarkdown: dco_decode_String(arr[3]),
      rawInput: dco_decode_String(arr[4]),
      completed: dco_decode_list_String(arr[5]),
      issues: dco_decode_list_String(arr[6]),
      plans: dco_decode_list_String(arr[7]),
      date: dco_decode_String(arr[8]),
      apiLogEnabled: dco_decode_bool(arr[9]),
    );
  }

  @protected
  FimCompleteRequest dco_decode_fim_complete_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FimCompleteRequest(
      appDataDir: dco_decode_String(arr[0]),
      provider: dco_decode_ai_provider(arr[1]),
      model: dco_decode_ai_model(arr[2]),
      prompt: dco_decode_String(arr[3]),
      suffix: dco_decode_String(arr[4]),
      apiLogEnabled: dco_decode_bool(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AiModel> dco_decode_list_ai_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ai_model).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MemoryChatRequest dco_decode_memory_chat_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MemoryChatRequest(
      appDataDir: dco_decode_String(arr[0]),
      provider: dco_decode_ai_provider(arr[1]),
      model: dco_decode_ai_model(arr[2]),
      question: dco_decode_String(arr[3]),
      contextMarkdown: dco_decode_String(arr[4]),
      apiLogEnabled: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ModelListResult dco_decode_model_list_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ModelListResult(
      ok: dco_decode_bool(arr[0]),
      models: dco_decode_list_ai_model(arr[1]),
      errorCode: dco_decode_String(arr[2]),
      errorMessage: dco_decode_String(arr[3]),
    );
  }

  @protected
  ProviderTestResult dco_decode_provider_test_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProviderTestResult(
      ok: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      errorCode: dco_decode_String(arr[2]),
    );
  }

  @protected
  ReportRequest dco_decode_report_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ReportRequest(
      appDataDir: dco_decode_String(arr[0]),
      provider: dco_decode_ai_provider(arr[1]),
      model: dco_decode_ai_model(arr[2]),
      sourceMarkdown: dco_decode_String(arr[3]),
      periodLabel: dco_decode_String(arr[4]),
      apiLogEnabled: dco_decode_bool(arr[5]),
    );
  }

  @protected
  StructuredNoteRequest dco_decode_structured_note_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StructuredNoteRequest(
      appDataDir: dco_decode_String(arr[0]),
      provider: dco_decode_ai_provider(arr[1]),
      model: dco_decode_ai_model(arr[2]),
      input: dco_decode_String(arr[3]),
      apiLogEnabled: dco_decode_bool(arr[4]),
    );
  }

  @protected
  StructuredNoteResult dco_decode_structured_note_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return StructuredNoteResult(
      ok: dco_decode_bool(arr[0]),
      completed: dco_decode_list_String(arr[1]),
      issues: dco_decode_list_String(arr[2]),
      plans: dco_decode_list_String(arr[3]),
      rawContent: dco_decode_String(arr[4]),
      errorCode: dco_decode_String(arr[5]),
      errorMessage: dco_decode_String(arr[6]),
      inputTokens: dco_decode_i_32(arr[7]),
      outputTokens: dco_decode_i_32(arr[8]),
      cachedTokens: dco_decode_i_32(arr[9]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AiModel sse_decode_ai_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    return AiModel(modelId: var_modelId, displayName: var_displayName);
  }

  @protected
  AiProvider sse_decode_ai_provider(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_apiKey = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_apiPath = sse_decode_String(deserializer);
    return AiProvider(
      id: var_id,
      name: var_name,
      protocol: var_protocol,
      apiKey: var_apiKey,
      baseUrl: var_baseUrl,
      apiPath: var_apiPath,
    );
  }

  @protected
  AiTextResult sse_decode_ai_text_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_errorCode = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    var var_inputTokens = sse_decode_i_32(deserializer);
    var var_outputTokens = sse_decode_i_32(deserializer);
    var var_cachedTokens = sse_decode_i_32(deserializer);
    var var_providerName = sse_decode_String(deserializer);
    var var_modelId = sse_decode_String(deserializer);
    return AiTextResult(
      ok: var_ok,
      content: var_content,
      errorCode: var_errorCode,
      errorMessage: var_errorMessage,
      inputTokens: var_inputTokens,
      outputTokens: var_outputTokens,
      cachedTokens: var_cachedTokens,
      providerName: var_providerName,
      modelId: var_modelId,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AiModel sse_decode_box_autoadd_ai_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ai_model(deserializer));
  }

  @protected
  AiProvider sse_decode_box_autoadd_ai_provider(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ai_provider(deserializer));
  }

  @protected
  DailyMergeRequest sse_decode_box_autoadd_daily_merge_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_daily_merge_request(deserializer));
  }

  @protected
  FimCompleteRequest sse_decode_box_autoadd_fim_complete_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fim_complete_request(deserializer));
  }

  @protected
  MemoryChatRequest sse_decode_box_autoadd_memory_chat_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_memory_chat_request(deserializer));
  }

  @protected
  ReportRequest sse_decode_box_autoadd_report_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_report_request(deserializer));
  }

  @protected
  StructuredNoteRequest sse_decode_box_autoadd_structured_note_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_structured_note_request(deserializer));
  }

  @protected
  DailyMergeRequest sse_decode_daily_merge_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appDataDir = sse_decode_String(deserializer);
    var var_provider = sse_decode_ai_provider(deserializer);
    var var_model = sse_decode_ai_model(deserializer);
    var var_existingMarkdown = sse_decode_String(deserializer);
    var var_rawInput = sse_decode_String(deserializer);
    var var_completed = sse_decode_list_String(deserializer);
    var var_issues = sse_decode_list_String(deserializer);
    var var_plans = sse_decode_list_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_apiLogEnabled = sse_decode_bool(deserializer);
    return DailyMergeRequest(
      appDataDir: var_appDataDir,
      provider: var_provider,
      model: var_model,
      existingMarkdown: var_existingMarkdown,
      rawInput: var_rawInput,
      completed: var_completed,
      issues: var_issues,
      plans: var_plans,
      date: var_date,
      apiLogEnabled: var_apiLogEnabled,
    );
  }

  @protected
  FimCompleteRequest sse_decode_fim_complete_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appDataDir = sse_decode_String(deserializer);
    var var_provider = sse_decode_ai_provider(deserializer);
    var var_model = sse_decode_ai_model(deserializer);
    var var_prompt = sse_decode_String(deserializer);
    var var_suffix = sse_decode_String(deserializer);
    var var_apiLogEnabled = sse_decode_bool(deserializer);
    return FimCompleteRequest(
      appDataDir: var_appDataDir,
      provider: var_provider,
      model: var_model,
      prompt: var_prompt,
      suffix: var_suffix,
      apiLogEnabled: var_apiLogEnabled,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AiModel> sse_decode_list_ai_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AiModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ai_model(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MemoryChatRequest sse_decode_memory_chat_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appDataDir = sse_decode_String(deserializer);
    var var_provider = sse_decode_ai_provider(deserializer);
    var var_model = sse_decode_ai_model(deserializer);
    var var_question = sse_decode_String(deserializer);
    var var_contextMarkdown = sse_decode_String(deserializer);
    var var_apiLogEnabled = sse_decode_bool(deserializer);
    return MemoryChatRequest(
      appDataDir: var_appDataDir,
      provider: var_provider,
      model: var_model,
      question: var_question,
      contextMarkdown: var_contextMarkdown,
      apiLogEnabled: var_apiLogEnabled,
    );
  }

  @protected
  ModelListResult sse_decode_model_list_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_models = sse_decode_list_ai_model(deserializer);
    var var_errorCode = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    return ModelListResult(
      ok: var_ok,
      models: var_models,
      errorCode: var_errorCode,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  ProviderTestResult sse_decode_provider_test_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_errorCode = sse_decode_String(deserializer);
    return ProviderTestResult(
      ok: var_ok,
      message: var_message,
      errorCode: var_errorCode,
    );
  }

  @protected
  ReportRequest sse_decode_report_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appDataDir = sse_decode_String(deserializer);
    var var_provider = sse_decode_ai_provider(deserializer);
    var var_model = sse_decode_ai_model(deserializer);
    var var_sourceMarkdown = sse_decode_String(deserializer);
    var var_periodLabel = sse_decode_String(deserializer);
    var var_apiLogEnabled = sse_decode_bool(deserializer);
    return ReportRequest(
      appDataDir: var_appDataDir,
      provider: var_provider,
      model: var_model,
      sourceMarkdown: var_sourceMarkdown,
      periodLabel: var_periodLabel,
      apiLogEnabled: var_apiLogEnabled,
    );
  }

  @protected
  StructuredNoteRequest sse_decode_structured_note_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appDataDir = sse_decode_String(deserializer);
    var var_provider = sse_decode_ai_provider(deserializer);
    var var_model = sse_decode_ai_model(deserializer);
    var var_input = sse_decode_String(deserializer);
    var var_apiLogEnabled = sse_decode_bool(deserializer);
    return StructuredNoteRequest(
      appDataDir: var_appDataDir,
      provider: var_provider,
      model: var_model,
      input: var_input,
      apiLogEnabled: var_apiLogEnabled,
    );
  }

  @protected
  StructuredNoteResult sse_decode_structured_note_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_completed = sse_decode_list_String(deserializer);
    var var_issues = sse_decode_list_String(deserializer);
    var var_plans = sse_decode_list_String(deserializer);
    var var_rawContent = sse_decode_String(deserializer);
    var var_errorCode = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    var var_inputTokens = sse_decode_i_32(deserializer);
    var var_outputTokens = sse_decode_i_32(deserializer);
    var var_cachedTokens = sse_decode_i_32(deserializer);
    return StructuredNoteResult(
      ok: var_ok,
      completed: var_completed,
      issues: var_issues,
      plans: var_plans,
      rawContent: var_rawContent,
      errorCode: var_errorCode,
      errorMessage: var_errorMessage,
      inputTokens: var_inputTokens,
      outputTokens: var_outputTokens,
      cachedTokens: var_cachedTokens,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ai_model(AiModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelId, serializer);
    sse_encode_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_ai_provider(AiProvider self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.apiKey, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_String(self.apiPath, serializer);
  }

  @protected
  void sse_encode_ai_text_result(AiTextResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.errorCode, serializer);
    sse_encode_String(self.errorMessage, serializer);
    sse_encode_i_32(self.inputTokens, serializer);
    sse_encode_i_32(self.outputTokens, serializer);
    sse_encode_i_32(self.cachedTokens, serializer);
    sse_encode_String(self.providerName, serializer);
    sse_encode_String(self.modelId, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ai_model(AiModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ai_model(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ai_provider(
    AiProvider self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ai_provider(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_daily_merge_request(
    DailyMergeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_daily_merge_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_fim_complete_request(
    FimCompleteRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fim_complete_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_memory_chat_request(
    MemoryChatRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_memory_chat_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_report_request(
    ReportRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_report_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_structured_note_request(
    StructuredNoteRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_structured_note_request(self, serializer);
  }

  @protected
  void sse_encode_daily_merge_request(
    DailyMergeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appDataDir, serializer);
    sse_encode_ai_provider(self.provider, serializer);
    sse_encode_ai_model(self.model, serializer);
    sse_encode_String(self.existingMarkdown, serializer);
    sse_encode_String(self.rawInput, serializer);
    sse_encode_list_String(self.completed, serializer);
    sse_encode_list_String(self.issues, serializer);
    sse_encode_list_String(self.plans, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_bool(self.apiLogEnabled, serializer);
  }

  @protected
  void sse_encode_fim_complete_request(
    FimCompleteRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appDataDir, serializer);
    sse_encode_ai_provider(self.provider, serializer);
    sse_encode_ai_model(self.model, serializer);
    sse_encode_String(self.prompt, serializer);
    sse_encode_String(self.suffix, serializer);
    sse_encode_bool(self.apiLogEnabled, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ai_model(List<AiModel> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ai_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_memory_chat_request(
    MemoryChatRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appDataDir, serializer);
    sse_encode_ai_provider(self.provider, serializer);
    sse_encode_ai_model(self.model, serializer);
    sse_encode_String(self.question, serializer);
    sse_encode_String(self.contextMarkdown, serializer);
    sse_encode_bool(self.apiLogEnabled, serializer);
  }

  @protected
  void sse_encode_model_list_result(
    ModelListResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_list_ai_model(self.models, serializer);
    sse_encode_String(self.errorCode, serializer);
    sse_encode_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_provider_test_result(
    ProviderTestResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.errorCode, serializer);
  }

  @protected
  void sse_encode_report_request(ReportRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appDataDir, serializer);
    sse_encode_ai_provider(self.provider, serializer);
    sse_encode_ai_model(self.model, serializer);
    sse_encode_String(self.sourceMarkdown, serializer);
    sse_encode_String(self.periodLabel, serializer);
    sse_encode_bool(self.apiLogEnabled, serializer);
  }

  @protected
  void sse_encode_structured_note_request(
    StructuredNoteRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appDataDir, serializer);
    sse_encode_ai_provider(self.provider, serializer);
    sse_encode_ai_model(self.model, serializer);
    sse_encode_String(self.input, serializer);
    sse_encode_bool(self.apiLogEnabled, serializer);
  }

  @protected
  void sse_encode_structured_note_result(
    StructuredNoteResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_list_String(self.completed, serializer);
    sse_encode_list_String(self.issues, serializer);
    sse_encode_list_String(self.plans, serializer);
    sse_encode_String(self.rawContent, serializer);
    sse_encode_String(self.errorCode, serializer);
    sse_encode_String(self.errorMessage, serializer);
    sse_encode_i_32(self.inputTokens, serializer);
    sse_encode_i_32(self.outputTokens, serializer);
    sse_encode_i_32(self.cachedTokens, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
